services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    disk:
      name: todo-db-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 5000
      - key: DB_PATH
        value: /var/data/todos.db

  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        sync: false
      - key: REACT_APP_API_URL
        sync: false
